### ISSUE TITLE
Not working with ruby 2.1.2

### ISSUE THREAD

**Issue by masha256** [duckinator/sicuro#30]
Works fine on another machine of mine with ruby 1.9.3. Not so much on 2.1.2. Tested on ubuntu 14.04LTS.

<pre>
mike@localhost:~$ irb
2.1.2 :001 > require 'sicuro'
 => true
2.1.2 :002 > Sicuro.eval("p(1+1)").to_s.strip
[SICURO] Process #1308 still running in Eval#new.
 => "NameError: undefined method `singleton_class?' for class `Object'\n/usr/local/rvm/gems/ruby-2.1.2/gems/sicuro-0.20.0/lib/sicuro/base.rb:179:in `eval'\n(eval):1:in `block (3 levels) in _safe_eval'\n/usr/local/rvm/gems/ruby-2.1.2/gems/sicuro-0.20.0/lib/sicuro/base.rb:179:in `eval'\n/usr/local/rvm/gems/ruby-2.1.2/gems/sicuro-0.20.0/lib/sicuro/base.rb:179:in `block (3 levels) in _safe_eval'\n/usr/local/rvm/gems/ruby-2.1.2/gems/sicuro-0.20.0/lib/sicuro/base.rb:172:in `each'\n/usr/local/rvm/gems/ruby-2.1.2/gems/sicuro-0.20.0/lib/sicuro/base.rb:172:in `block (2 levels) in _safe_eval'\n/usr/local/rvm/gems/ruby-2.1.2/gems/sicuro-0.20.0/lib/sicuro/base.rb:171:in `module_eval'\n/usr/local/rvm/gems/ruby-2.1.2/gems/sicuro-0.20.0/lib/sicuro/base.rb:171:in `block in _safe_eval'\n/usr/local/rvm/gems/ruby-2.1.2/gems/sicuro-0.20.0/lib/sicuro/base.rb:160:in `each'\n/usr/local/rvm/gems/ruby-2.1.2/gems/sicuro-0.20.0/lib/sicuro/base.rb:160:in `_safe_eval'\n-e:3:in `<main>'"
</pre>
